artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1zmyziYpfhc-AcBRuvX77G6f2I2OZs6T7/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.csv


base_model:
  root_dir: models
  source_url: first_time
  local_model_file: models/model.pkl
  model_name: alminilmv6


